version: "3"

services:

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wp

  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: always
    volumes: 
        - "./themes/:/var/www/html/wp-content/themes/"
        #- "./plugins/:/var/www/html/wp-content/plugins/"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD', 'direct' );
    ports:
      - 80:80
      - 443:443
    networks:
      - wp

networks:
  wp:
volumes:
  db_data: